import Head from 'next/head'
import { useEffect, useState } from 'react'
import DefaultLayout from './../components/layouts/DefaultLayout';

export default function Home() {
  const [time, setTime] = useState(null)
  useEffect(() => {
    setInterval(() => {
      setTime(new Date().toLocaleTimeString())
    }, 1000)
  }, [])
  return (
    
    <DefaultLayout>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="text-red-500 text-2xl">{time}</div>
      </main>

      <footer>
        
      </footer>
    </DefaultLayout>
  )
}
